---
- name: remote device config backup to a file
  hosts: I_Building_B
  gather_facts: false
  connection: local

  tasks:
   - name: show device infomation
     ios_command:
       commands:
         - show clock
         - show version
         - show inventory
         - show running-config

     register: print_output

   - debug: var=print_output.stdout_lines

   - name: Save content to a file
     lineinfile: 
      dest: /etc/ansible/device_config/{{ inventory_hostname }}.ios
      line: "{{ item }}"
     with_items:
      - "{{ print_output.stdout[0] }}"
      - "{{ print_output.stdout[1] }}"
      - "{{ print_output.stdout[2] }}"
      - "{{ print_output.stdout[3] }}"