---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
        backup_options:
          dir_path: "/etc/ansible/device_config/"
          filename: "{{ inventory_hostname }}.ios"
      register: config_output
