---
- name: BACKUP JUNOS CONFIGURATIONS
  hosts: juniper
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      raw: "show configuration | display set | no-more"
      register: config_output
    
    - name: COPY FILE TO DEVICE_CONFIG
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "/etc/ansible/device_config/{{ inventory_hostname }}.jun"
