---
- name: BACKUP JUNOS CONFIGURATIONS
  hosts: juniper
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      junos_config:
        backup: yes
        backup_options:
          dir_path: "/etc/ansible/device_config/"
          filename: "{{ inventory_hostname }}.jun"
        provider: 
          connection: network_cli
      register: config_output
