---
- name: run multiple commands on remote devices
  hosts: I_Building_B
  gather_facts: false
  connection: local

  tasks:
   - name: show clock and show ip int brief
     ios_command:
       commands:
         - show clock
         - show ip int brief

     register: print_output

   - debug: var=print_output.stdout_lines
